name: CI
on:
    push:
        branches: [main]

jobs:
    test:
        name: Test, Build, Deploy
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"

            - name: Prepare
              run: npm install

            - name: Test
              run: npm run-script test

            - name: Build
              run: npm run-script release

            - name: Deploy
              env:
                  REMOTE_SSH_KEY: ${{ secrets.REMOTE_SSH_KEY }}
                  REMOTE_IP: ${{ secrets.REMOTE_IP }}
              run: |
                  eval $(ssh-agent -s)
                  ssh-add <(echo "$REMOTE_SSH_KEY")
                  ssh "$REMOTE_IP" touch git_test
                  ssh-agent -k
                  ls
